server:
  port: ${PORT:8082}

spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/productdb}

inventory-service:
  url: http://${INVENTORY_SERVICE_HOSTPORT:inventory-service:8083}
